image: "registry.gitlab.com/cipres/ipfs-void-storm:latest"

stages:
  - build

build:
  stage: build
  script:
    - python3 -m pip install --upgrade pip
    - python3 -m venv venv

    - source venv/bin/activate
    - pip install wheel
    - pip install -r requirements-dev.txt
    - pip install -r requirements.txt

    - flake8 aioipfs tests --count --select=E9,F63,F7,F82 --show-source --statistics
    - python3 setup.py build install

    - pytest -v -s tests
    - python setup.py sdist bdist_wheel

    - |-
      if [[ "$CI_COMMIT_MESSAGE" =~ '[deploy]' ]]; then
        pip install twine
        twine upload dist/*
      fi

  artifacts:
    paths:
      - dist/*.whl
