stages:
  - build
  - pypi

variables:
  PATH: "/opt/ipfs/bin:/usr/bin:/bin:/sbin"

.build:
  parallel:
    matrix:
      # This is the list of go-ipfs/kubo versions that
      # we run unit tests against

      - IPFSD_TEST_RELEASE: [
          kubo-0.20.0,
          kubo-0.22.0,
          kubo-0.24.0,
          kubo-0.26.0,
          kubo-0.27.0
        ]

  script:
    - apt-get update
    - apt-get install -qy --force-yes python3-pip python3-venv
    - mkdir -p /opt/ipfs/bin

    - |-
      # Match go-ipfs version number
      if [[ "$IPFSD_TEST_RELEASE" =~ go-ipfs-([0-9].[0-9]+.[0-9]+) ]]; then
        VER="${BASH_REMATCH[1]}"

        curl -o go-ipfs.tar.gz \
          https://dist.ipfs.tech/go-ipfs/v${VER}/go-ipfs_v${VER}_linux-amd64.tar.gz
        tar -xvf go-ipfs.tar.gz && cp go-ipfs/ipfs /opt/ipfs/bin
      fi

      # Match kubo version number (will work with x.xx.xx)
      if [[ "$IPFSD_TEST_RELEASE" =~ kubo-([0-9].[0-9]+.[0-9]+) ]]; then
        VER="${BASH_REMATCH[1]}"

        curl -o kubo.tar.gz \
          https://dist.ipfs.tech/kubo/v${VER}/kubo_v${VER}_linux-amd64.tar.gz
        tar -xvf kubo.tar.gz && cp kubo/ipfs /opt/ipfs/bin
      fi

    - ipfs version

    - python3 -m venv venv
    - source venv/bin/activate
    - python -m pip install --upgrade pip

    - pip install wheel build
    - pip install '.[car,dev]'

    - flake8 aioipfs tests --count --select=E9,F63,F7,F82 --show-source --statistics
    - mypy aioipfs
    - pytest --cov --cov-report=term --cov-report=xml:coverage.xml -v -s tests

    - python -m build

  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  artifacts:
    paths:
      - dist/*.whl

build-3.9:
  extends: ".build"
  stage: "build"
  image: "python:3.9-bullseye"
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[test-all\]/ || $CI_COMMIT_MESSAGE =~ /\[test-39\]/
      when: always

build-3.11:
  extends: ".build"
  stage: "build"
  image: "python:3.11"
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[test-all\]/ || $CI_COMMIT_MESSAGE =~ /\[test-311\]/
      when: always

build-3.12:
  extends: ".build"
  stage: "build"
  image: "python:3.12"
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[test-all\]/ || $CI_COMMIT_MESSAGE =~ /\[test-312\]/
      when: always

pypi:
  image: "python:3.9-bullseye"
  stage: pypi
  cache: {}
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[publish\]/ || $CI_COMMIT_MESSAGE =~ /\[pypi\]/
      when: always
  before_script:
    - apt-get update
    - apt-get install -qy --force-yes python3-pip python3-venv
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - python -m pip install --upgrade pip

    - pip install .
    - pip install -U twine build

    - python -m build

    - |-
      echo "Branch is: $CI_COMMIT_BRANCH"

      if [[ "$CI_COMMIT_BRANCH" == "master" ]]; then
        twine check dist/*.whl
        twine upload dist/*
      else
        twine check dist/*.whl
      fi
